name: "Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upgrade pip
      run: |
        python3 -m pip install --upgrade pip
    - name: Install python module requirements
      run: |
        python3 -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        python3 -m pip install pylint
        pylint blueflame.py
        echo "Create tests to run here"
