name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        pip3 install -r requirements.txt
        pip3 install pylint
        pylint bluflame.py
        echo "Create tests to run here"
